name = "qdesign-manager"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

# 静态资源
assets = { directory = ".open-next/assets", binding = "ASSETS" }

# D1 Database配置
[[d1_databases]]
binding = "DB"
database_name = "qdesign-db"
database_id = "1e20b474-562f-4a73-a5fa-6981eade6b78"

# R2 Bucket配置
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "qdesign-models"

[vars]
ENVIRONMENT = "production"
